### ISSUE TITLE
Investigation on development of milestones and week wise timeline creation for GSoC 2021 - OpenMF - Frontend and Backend and improvements

### ISSUE THREAD

**Issue by shivanshuraj1333** [scorelab/OpenMF#167]
**This is an investigative task which targets to redefine GSoC'21 milestones**

It is required for the student to divide the different tasks associated with GSoC 2021 - OpenMF - Frontend and Backend and improvements and come up with a week wise timeline to achieve various milestones.
The tasks will be updated on the project's Kanban Board once the coding period officially starts; this approach aligns with agile strategy, helping students provide deliverables on time and helps in the overall evaluation of different tasks.
The initial research on defining tasks and milestones is captured in this [document](https://docs.google.com/document/d/1_sxxry-vwcLAd9TP-6EbbArBTvC1hR7t-A3FAiXjooA/edit?usp=sharing)

**Comment by sachinsom93** [comment]
Closing this issue as , the milestones have been modified on in the given document link:)
