### ISSUE TITLE
Extract all data from rooted Android device not working

### ISSUE THREAD

**Issue by swapnalshahil** [scorelab/OpenMF#170]
**Describe the bug**
Extracting all data from the command line from single command not working.
Present condition: Right now we have to extract separately one by one.
Here is the command:
`python3 collector.py --option all --session_name CaseNo1​`

**Expected behavior**
It should extract all data like Facebook, WhatsApp, etc.

**Screenshots**
<img width="166" alt="2021-06-06" src="https://user-images.githubusercontent.com/58564017/120913814-9b321e80-c6b7-11eb-90bb-5e9fb447e124.png">

**Comment by shivanshuraj1333** [comment]
@sachinsom93 can take a look into this?
For eg if we extract fb data by using dedicated command for extracting fb data then it works fine and we can see the fb messages data but when we extract all the data we don't see fb messages. (may be happening with other use-cases as well).
@swapnalshahil you may provide more context on it and discuss the issue with @sachinsom93 to make him familiar with the exact bug that we're seeing.

**Comment by swapnalshahil** [comment]
@shivanshu1333  sir! I was saying the same thing. Like when we extract all data from cmd we don't see any Facebook, WhatsApp, etc data as data/db remains empty. Above screenshot shows the same.
