### ISSUE TITLE
converter.py does not store the extracted data in right directory.

### ISSUE THREAD

**Issue by shivanshuraj1333** [scorelab/OpenMF#18]
**Describe the bug**
On running converter.py command as `python3 converter.py ~/OpenMF/case_001_john_snow/db/Contact.db ~/OpenMF/data` where `case_001_john_snow` contains `db/*.db` and `report.txt` extracted after running `collector.py`, the converted `.tsv` files are stored in project directory i.e. `~/OpenMF/` and not in the directory provided by the user i.e. `~/OpenMF/data`.

**Expected behavior**
The converted files should be stored in the path described i.e. `~/OpenMF/data` in the example described above.

**Improved behavior**
For ease of data access and to maintain the data hierarchy the extracted files should be stored inside that particular case directory within the data folder.
For e.g. in the above case, the newly extracted data should be stored in `~/OpenMF/data/case_001_john_snow/Contact`.
New folders should be created inside the data folder to properly store extracted data, it should also replace the existing files with the new updated files of the same case.

**Comment by vivonk** [comment]
Go for it @shivanshu1333

**Comment by shivanshuraj1333** [comment]
Closing the issue as it is resolved in PR#19.
