### ISSUE TITLE
Redundant folder creation every time we run collector.py

### ISSUE THREAD

**Issue by shivanshuraj1333** [scorelab/OpenMF#20]
**Describe the bug**
Whenever we run `collector.py` to extract `.db` files or to generate report, a redundant folder is created apart from one that is defined by the user during running the command.
For e.g.,
If we run `collector.py --option all --session_name case_001_john_snow` all the extracted `.db` files, `report`, and `report.txt` get stored in `case_001_john_snow/db`, `case_001_john_snow/report` and `case_001_john_snow` folders respectively but a redundant folder with device name is created (`Xiaomi_Redmi Note 4_2020-02-17_12.15.52` and `Xiaomi_Redmi Note 4_2020-02-17_12.15.52/db` in my case as I am using Xiaomi Redmi Note 4 for testing).

**Note:-** _If we run collector.py X times then these redundant folders will be created X times in the project directory. And each of that folder is empty consisting of only an empty db folder._

**To Reproduce**
Run `collector.py` either one time or many times, even if we don't provide sufficient arguments to `collector.py`, the redundant folders are created.

**Expected behavior**
Only that folder which is defined by the user while running `collector.py` should be created.
In the above example only `case_001_john_snow/db`, `case_001_john_snow/report` and `case_001_john_snow` should be created. `Xiaomi_Redmi Note 4_2020-02-17_12.15.52` and `Xiaomi_Redmi Note 4_2020-02-17_12.15.52/db` should not be created as they are redundent.

**Screenshots**
![Screenshot from 2020-02-17 12-53-12](https://user-images.githubusercontent.com/26167974/74632075-8eb54a00-5184-11ea-9634-ef0900235b85.png)
As explained in the above example if we run `collector.py --option all --session_name xcase1` and `collector.py --report xcase1` for xcase1, xcase2 and xcase3 these empty redundant folders are created 6 times (as `collector.py` is executed 6 times).

**Comment by vivonk** [comment]
Correct, are you working on it @shivanshu1333 ?

**Comment by shivanshuraj1333** [comment]
Yes, I have fixed this issue in PR #21.

**Comment by shivanshuraj1333** [comment]
Closing the issue as it is resolved by PR #21.
