### ISSUE TITLE
security bug

### ISSUE THREAD

**Issue by shivanshuraj1333** [scorelab/OpenMF#240]
We need to remove the google API key from the file https://github.com/scorelab/OpenMF/React-frontend/src/components/Management/LocationReport.js and figure out a different method without exposing the private key and avoid the security threat.

**Comment by shivanshuraj1333** [comment]
Info: The Google API key is created and owned by @swapnalshahil (student at IIT G)

**Comment by swapnalshahil** [comment]
@shivanshu1333 sir! It's ok if this key is present there as it is free without any limit. But there is also one method to hide it by saving it in .env but again another person will need to generate an API key whenever a new person comes.
There are millions of these keys available and are used by people on internet.

**Comment by shivanshuraj1333** [comment]
If you're comfortable, in that case I'm closing the issue.
