### ISSUE TITLE
[Frontend] Navbar Login and Register button not working

### ISSUE THREAD

**Issue by swapnalshahil** [scorelab/OpenMF#258]
**Describe the bug**
Presently navbar LOGIN BUTTON is not working properly. After login, it shows the error "Something went wrong". Instead of this, it should redirect to the main landing page of respective roles.

**To Reproduce**
1. Click on Login/Register button
2. Fill the requirements
4. See error.

**Expected behavior**
It should work correctly for Login and register for the authentication process. Also, check other buttons if they are correctly routed or not.

**Comment by chennupativiman** [comment]
Hi..Can I work on this?

**Comment by swapnalshahil** [comment]
@chennupativiman yes go on!
