### ISSUE TITLE
Create web client for OpenMF (GSoC 2020)

### ISSUE THREAD

**Issue by shivanshuraj1333** [scorelab/OpenMF#37]
### This issue is created to give light on the work to be done during GSoC 2020.
**Project deliverables are as follows:-**
- Modify the current code base to make a strong robust command-line tool for OpenMF.
- Design and Implement a Client-side Framework for Web Client.
- Design and Implement Login, Admin, Management, and Extractor pages (refer to Fig 1 and Fig 2).
- Implementation of backend from scratch and writing different APIs in the flask framework.
- Implementation of different roles (Admin, Management, Extractor) from scratch.
- Extending the functionality of OpenMF to include download, upload, and management of files on the server.
- Implementation Access Control Lists (ACL) to manage file permissions among users by Admin.
- Design and implement a Database model, relation mapping (ORM) in the database to incorporate the above functionalities in MySQL using the SQLAlchemy toolkit.
- Write a project wiki and update the user and developer documentation.
- Weekly blogs on medium.
![Screenshot from 2020-05-07 13-08-47](https://user-images.githubusercontent.com/26167974/81267405-0dbf6d80-9064-11ea-83a7-693eb2689941.png)
**<p align="center">Fig. 1</p>**
![Screenshot from 2020-05-07 13-08-48](https://user-images.githubusercontent.com/26167974/81269430-eae28880-9066-11ea-9b13-3353f1b169c1.png)
**<p align="center">Fig. 2</p>**

**Comment by vivonk** [comment]
@shivanshu1333 I have created new project for GSoC 2020 work. Now you can create sub-issues according to timelines and progress. Use project page for updating your progress with issues so that we can be updated centric :).
Project Link - https://github.com/scorelab/OpenMF/projects/2
Welcome onboard @shivanshu1333 :)

**Comment by shivanshuraj1333** [comment]
Okay, sure @vivonk 
Thanks :)

**Comment by shivanshuraj1333** [comment]
The issue is resolved, closing it now.
