### ISSUE TITLE
Add support for Centralized Database(CDB) incorporating the required Database Model with Object-relational mapping (ORM)

### ISSUE THREAD

**Issue by shivanshuraj1333** [scorelab/OpenMF#42]
**What all is required?**

>     Implement a Centralized Database of OpenMF in MySQL using the SQLAlchemy toolkit
The Database design is required to be robust and responsive so that, it can incorporate the following functionalities.
> 1. Highly responsive towards any REST APIs making a query to the database
> 2. Able to achieve minimum latency by implementing required functions with optimized time complexity
> 3. Maintain a proper Object-relational mapping (ORM)
> 4. Designed in a way that it can be easily hosted in Database Server

**<p align="center">The Database design is required to follow the given Database schema</p>**

<p align="center">
<img src="https://user-images.githubusercontent.com/26167974/90098581-325b6d80-dd56-11ea-939f-3dec56808aad.png">
</p>

<p align="center">
<img src="https://user-images.githubusercontent.com/26167974/90098597-38514e80-dd56-11ea-90a8-c12cf590e1e9.png">
</p>

The details of which are mentioned in issue #37

**Comment by vivonk** [comment]
Data Structure is self explanatory I guess and good job on that @shivanshu1333 . Also, keep these data model designs in the docs folder so that we can have them for further :)

**Comment by shivanshuraj1333** [comment]
Okay, will surely do that.

**Comment by shivanshuraj1333** [comment]
Issue resolved, clossing it now.
