### ISSUE TITLE
Documentation needs update!

### ISSUE THREAD

**Issue by swapnalshahil** [scorelab/OpenMF#46]
I think README.md should provide more information like How to set up the backend for this project? How to set the frontend of this project? This will help others to easily dive into the project.

**Comment by shivanshuraj1333** [comment]
@swapnalshahil for backend there is a separate Readme [here](https://github.com/scorelab/OpenMF/tree/master/flask-backend) you may go ahead with creating a separate Readme for Frontend just like backend. Also you can modify the main Readme file to contain links of both frontend and backend.

**Comment by swapnalshahil** [comment]
Ok, will do it soon! Thanks!
