### ISSUE TITLE
Move Footer content to Sidebar for better UI

### ISSUE THREAD

**Issue by amlannandy** [scorelab/OpenMF#48]
**Is your feature request related to a problem? Please describe.**
The footer is occupying unnecessary space. Which reduces space for the main content.

**Describe the solution you'd like**
We can improve the UI of the sidebar and add the contents of the footer to it.

**Comment by shivanshuraj1333** [comment]
Not necessary, please discuss before making any code change to save time. I've closed the PR, closing this issue as well.
