### ISSUE TITLE
[Frontend] Start redux implementation by creating an alerts reducer

### ISSUE THREAD

**Issue by amlannandy** [scorelab/OpenMF#51]
**Describe the solution you'd like**
Since we're going to use redux for state management, we can start by implementing an alerts reducer, so that for each error/failed API request, we can display an alert from anywhere in the app with a single line.
Expanding on this, if we use something like axios for API calls, we can set up an intercepter to automatically catch all failed requests and display the error message sent by the API as an alert. This way, we won't have to manually handle error cases in each API call we make.

**Example**

![alert](https://user-images.githubusercontent.com/45410599/105992110-b1591e00-60ca-11eb-9fb7-4b15b3a910d3.png)

**Comment by amlannandy** [comment]
@shivanshu1333 Hello. What are your thoughts about this? Can we implement something like this for the project?

**Comment by shivanshuraj1333** [comment]
Sure, we can go ahead with the implementation of an alert reducer.
