### ISSUE TITLE
Alert not imported

### ISSUE THREAD

**Issue by MehtaManan07** [scorelab/OpenMF#54]
**Describe the bug**
A small bug. Alert was not imported in App.js.

**To Reproduce**
1. Go to 'App.js'
2. Import App.js there
3. And as it is a core component, I have shifted the component to components/core

**Expected behavior**
The app should start properly

**Comment by amlannandy** [comment]
@shivanshu1333 Hey! I think this issue is already resolved. So we can close this.

**Comment by b-thebest** [comment]
Can I work on this issue ?

**Comment by shivanshuraj1333** [comment]
hey @b-thebest PR for this issue is already merged, you can choose another issue.
