### ISSUE TITLE
[React] Implement Login and Register screens with auth redux reducer

### ISSUE THREAD

**Issue by amlannandy** [scorelab/OpenMF#55]
**Is your feature request related to a problem? Please describe.**
Login and Register screens are currently incomplete. Plan is to complete them along with continuing redux implementation with an authentication reducer.

**Comment by amlannandy** [comment]
@shivanshu1333 Hello. Please give it a look and let me know if I start working on it.

**Comment by shivanshuraj1333** [comment]
@amlannandy yes sure you can start working on this.
