### ISSUE TITLE
[Frontend] Implement Admin section

### ISSUE THREAD

**Issue by amlannandy** [scorelab/OpenMF#58]
**Is your feature request related to a problem? Please describe.**
The idea is to create a separate admin section in the app which will implement all functions from the user routes of the flask server.

**Describe the solution you'd like**
The PR will consist of implementation of the following features -
1. View all users
2.  View the details of each user
3. Create a new user
4. Update the role of an existing user
5. Delete an existing user.

**Additional context**
I'd like to work on this

**Comment by amlannandy** [comment]
@shivanshu1333 Hey! Please let me know your thoughts about this. If you think we can implement it, then please assign it to me and I can start the work.

**Comment by amlannandy** [comment]
@shivanshu1333 Hey. Can I start work on this? It's a big PR so I wanted to get your approval first.

**Comment by sachinsom93** [comment]
Hey hi @amlannandy, If you didn't start the work,then can I work on this issue ?

**Comment by amlannandy** [comment]
> Hey hi @amlannandy, If you didn't start the work,then can I work on this issue ?

@sachinsom93 Hi! Actually, I just opened a PR for it. :sweat_smile:
