### ISSUE TITLE
[frontend]: Creating a frontend for profile page

### ISSUE THREAD

**Issue by sachinsom93** [scorelab/OpenMF#60]
**Is your feature request related to a problem? Please describe.**
There should be a profile page for each user, so the idea is to create a page for profile that would contain all the information regarding user.

**Describe the solution you'd like**
This issue will deal with:
1. Creating frontend for profile page
2. Getting profile page information from flask server

**Describe alternatives you've considered**

**Additional context**
I would love to work on this issue.

**Comment by sachinsom93** [comment]
Hi @shivanshu1333, I am Sachin som. I am a 3rd year ECE B.tech undergraduate. I found this community interesting for open source contribution as it contains project that is pretty much lined with my skills. I would love to contribute to this project.
Kindly look on this issue and please let me know that can I start working on this issue ?

**Comment by neelesh17** [comment]
Hey @shivanshu1333, I would also like to work on this issue?

**Comment by sachinsom93** [comment]
Closing this issue, as there is already a issue related this.
